### ISSUE TITLE
مشكلة في اظهار كامل الخريطة 

### ISSUE THREAD

**Issue by Ramadanali** [amgadali/Rasim#6]
عند اضافة طبقة من نوع الشيب فايل وتم اضافة طبقة جرافيك بنقاط احداثي ومثلا هذا الاحداثي بعيد عن مساحة الخريطة 

وتم عمل اظها ركامل الخريطة  يوقم باظهار الشيب فايل فقط او الصورة الفضائية 

اي انه لا ياخذ طبقة الجرافيك في الاعتبار عند عمل اظهار كامل الخريطة 
zoom extend

**Comment by amgadali** [comment]
طبقات الجرافك لا يمكن حساب النطاق الخاص بها ولذلك لا تظهر
