### ISSUE TITLE
مشكلة عند عمل زووم اوت 

### ISSUE THREAD

**Issue by Ramadanali** [amgadali/Rasim#7]
عند عمل ززوم اوت علي الخريطة بحيث اختفت العناضر المرسومة تظهر رساله حدث خطا في رسم احد الطبقات 

![zoom_out](https://cloud.githubusercontent.com/assets/12684900/7923047/eae6dd6c-08b8-11e5-9417-d20d1d8d5257.jpg)

**Comment by amgadali** [comment]
ارسل لي ملف الخريطة وملف الصورة للتجربة
